In [101]:
import os

path = r"C:\Users\shiva reddy\Downloads\IMD_AP_Historical Rain Fall 2\IMD_AP_Historical Rain Fall"
files = os.listdir(path)
print(files)

['.DS_Store', 'AP_Village_Daily_Rainfall_21_r.csv', 'AP_Village_Daily_Rainfall_22_r.csv', 'AP_Village_Daily_Rainfall_23_r.csv', 'AP_Village_Daily_Rainfall_24_r.csv', 'AP_Village_Daily_Rainfall_25_r.csv']

In [102]:
import pandas as pd

df = pd.read_csv(path + "/AP_Village_Daily_Rainfall_21_r.csv")


df.head()

,district,mandal,village,rainfall_mm,date,centroid_lat,centroid_lon
0,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,17.379983,82.480743
1,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,17.341717,82.106768
2,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,18.189400,83.054974
3,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,14.389877,78.113202
4,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,14.279401,78.329855

In [103]:
df.columns

Index(['district', 'mandal', 'village', 'rainfall_mm', 'date', 'centroid_lat',
       'centroid_lon'],
      dtype='object')

In [104]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5689985 entries, 0 to 5689984
Data columns (total 7 columns):
 #   Column        Dtype
---  ------        -----
 0   district      object
 1   mandal        object
 2   village       object
 3   rainfall_mm   float64
 4   date          object
 5   centroid_lat  float64
 6   centroid_lon  float64
dtypes: float64(3), object(4)
memory usage: 303.9+ MB

        rainfall_mm  centroid_lat  centroid_lon
count  5.688525e+06  5.689985e+06  5.689985e+06
mean   3.261645e+00  1.585523e+01  8.031598e+01
std    9.773142e+00  1.836419e+00  1.951814e+00
min    0.000000e+00  1.266360e+01  7.694869e+01
25%    0.000000e+00  1.405345e+01  7.879384e+01
50%    0.000000e+00  1.567851e+01  7.945147e+01
75%    1.465441e+00  1.751153e+01  8.207938e+01
max    2.629529e+02  1.900453e+01  8.452812e+01

In [105]:
import pandas as pd
import glob

files = glob.glob("*.csv")

df_list = []

for file in files:
    temp = pd.read_csv(file, nrows=50000)   # ✅ only 50k rows per file
    temp.columns = temp.columns.str.strip().str.lower()
    df_list.append(temp)

final_df = pd.concat(df_list, ignore_index=True)

print("Shape:", final_df.shape)
final_df.head()

Shape: (1961, 14)

,district,mandal,village,rainfall_mm,date,centroid_lat,centroid_lon,year,month,day,rain_lag1,rain_lag2,predicted_rain,risk_level
0,S.P.S.Nellore,Marripadu,Brahmanapalle,4.344585,2022-01-01,15.641746,78.231144,2022,1,1,4.344585,4.344585,4.344585,LOW
1,S.P.S.Nellore,Marripadu,Brahmanapalle,4.344585,2022-01-01,15.413241,78.385809,2022,1,1,4.344585,4.344585,4.344585,LOW
2,S.P.S.Nellore,Marripadu,Brahmanapalle,1.339040,2022-01-02,15.075202,77.536737,2022,1,2,4.344585,4.344585,1.060378,LOW
3,S.P.S.Nellore,Marripadu,Brahmanapalle,1.339040,2022-01-02,14.416063,78.196952,2022,1,2,1.339040,4.344585,1.208955,LOW
4,S.P.S.Nellore,Marripadu,Brahmanapalle,1.339040,2022-01-02,16.077765,79.746478,2022,1,2,1.339040,1.339040,0.959786,LOW

In [106]:
import os
print(os.getcwd())

C:\Users\shiva reddy\AP_Rainfall_Task

In [107]:
print(os.listdir())

['.ipynb_checkpoints', 'App.py', 'app.py.rtf', 'AP_Rainfall.ipynb', 'canals', 'final_risk_map.html', 'rain_model.pkl', 'sample_data.csv', 'Untitled.ipynb']

In [108]:
import glob

path = r"C:\Users\shiva reddy\Downloads\IMD_AP_Historical Rain Fall 2\IMD_AP_Historical Rain Fall"

files = glob.glob(path + "/*.csv")

print(files)

['C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_21_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_22_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_23_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_24_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_25_r.csv']

In [109]:
import os

path = r"C:\Users\shiva reddy\Downloads\IMD_AP_Historical Rain Fall 2"

print(os.listdir(path))

['IMD_AP_Historical Rain Fall', '__MACOSX']

In [110]:
path = r"C:\Users\shiva reddy\Downloads\IMD_AP_Historical Rain Fall 2\IMD_AP_Historical Rain Fall"

print(os.listdir(path))

['.DS_Store', 'AP_Village_Daily_Rainfall_21_r.csv', 'AP_Village_Daily_Rainfall_22_r.csv', 'AP_Village_Daily_Rainfall_23_r.csv', 'AP_Village_Daily_Rainfall_24_r.csv', 'AP_Village_Daily_Rainfall_25_r.csv']

In [111]:
import os

files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.csv')]

print(files)

['C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_21_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_22_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_23_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_24_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_25_r.csv']

In [112]:
import pandas as pd

df_list = []

for file in files:
    temp = pd.read_csv(file, nrows=50000)
    temp.columns = temp.columns.str.strip().str.lower()
    df_list.append(temp)

print("Files loaded:", len(df_list))

Files loaded: 5

In [113]:
final_df = pd.concat(df_list, ignore_index=True)

print("Shape:", final_df.shape)
final_df.head()

Shape: (250000, 7)

,district,mandal,village,rainfall_mm,date,centroid_lat,centroid_lon
0,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,17.379983,82.480743
1,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,17.341717,82.106768
2,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,18.189400,83.054974
3,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,14.389877,78.113202
4,Alluri Sitharama Raju,Ananthagiri,Forest,0.0,2021-01-01,14.279401,78.329855

In [114]:
print(files)

['C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_21_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_22_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_23_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_24_r.csv', 'C:\\Users\\shiva reddy\\Downloads\\IMD_AP_Historical Rain Fall 2\\IMD_AP_Historical Rain Fall\\AP_Village_Daily_Rainfall_25_r.csv']

In [115]:
final_df = final_df.sample(50000)

print("New Shape:", final_df.shape)

New Shape: (50000, 7)

In [116]:
final_df['date'] = pd.to_datetime(final_df['date'])

final_df['year'] = final_df['date'].dt.year
final_df['month'] = final_df['date'].dt.month
final_df['day'] = final_df['date'].dt.day

In [117]:
final_df = final_df.sort_values(by=['village', 'date'])

In [118]:
final_df = final_df[final_df['rainfall_mm'] > 0]

In [119]:
final_df['rain_lag1'] = final_df.groupby('village')['rainfall_mm'].shift(1)
final_df['rain_lag2'] = final_df.groupby('village')['rainfall_mm'].shift(2)

final_df = final_df.dropna()

In [120]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

features = ['year','month','day','centroid_lat','centroid_lon','rain_lag1','rain_lag2']
target = 'rainfall_mm'

X = final_df[features]
y = final_df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

model = RandomForestRegressor(n_estimators=5)
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=5)

In [121]:
from sklearn.metrics import mean_absolute_error

pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))
print("Pred:", pred[:5])
print("Actual:", y_test[:5].values)

MAE: 1.3003588505420924
Pred: [2.17884906 1.0885899  2.17884906 1.45200962 2.54226878]
Actual: [2.9056885 1.0885899 2.9056885 1.0885899 1.0885899]

In [122]:
def get_risk(rain):
    if rain > 50:
        return "HIGH"
    elif rain > 20:
        return "MEDIUM"
    else:
        return "LOW"

In [123]:
final_df['predicted_rain'] = model.predict(X)
final_df['risk_level'] = final_df['predicted_rain'].apply(get_risk)

final_df[['village','predicted_rain','risk_level']].head()

      village  predicted_rain risk_level
63053  Forest       19.914168        LOW
65392  Forest        1.187019        LOW
64907  Forest       13.494371        LOW
65168  Forest        0.609158        LOW
62789  Forest       32.402183     MEDIUM

In [124]:
def predict_with_risk(year, month, day, lat, lon, lag1, lag2):
    rain = model.predict([[year, month, day, lat, lon, lag1, lag2]])[0]
    
    if rain > 20:
        risk = "HIGH"
    elif rain > 50:
        risk = "MEDIUM"
    else:
        risk = "LOW"
    
    return rain, risk
import warnings
warnings.filterwarnings('ignore')

### Final Output

In [125]:
predict_with_risk(2025, 7, 10, 15.5, 80.6, 5, 3)

(np.float64(0.9645963500000001), 'LOW')

In [126]:
predict_with_risk(2028, 12, 18, 20.5, 80.6, 2, 5)

(np.float64(1.6914357900000003), 'LOW')

### Canal

In [127]:
pip install geopandas folium shapely

Requirement already satisfied: geopandas in c:\users\public\anaconda1\lib\site-packages (1.1.3)
Requirement already satisfied: folium in c:\users\public\anaconda1\lib\site-packages (0.20.0)
Requirement already satisfied: shapely in c:\users\public\anaconda1\lib\site-packages (2.1.2)
Requirement already satisfied: numpy>=1.24 in c:\users\public\anaconda1\lib\site-packages (from geopandas) (2.1.3)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\public\anaconda1\lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\users\public\anaconda1\lib\site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=2.0.0 in c:\users\public\anaconda1\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\public\anaconda1\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: branca>=0.6.0 in c:\users\public\anaconda1\lib\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in c:\users\public\anaconda1\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: requests in c:\users\public\anaconda1\lib\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\users\public\anaconda1\lib\site-packages (from folium) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\public\anaconda1\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\public\anaconda1\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\public\anaconda1\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\public\anaconda1\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\public\anaconda1\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.8.3)
Requirement already satisfied: six>=1.5 in c:\users\public\anaconda1\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\public\anaconda1\lib\site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\public\anaconda1\lib\site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\public\anaconda1\lib\site-packages (from requests->folium) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

In [128]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\shiva reddy\AP_Rainfall_Task
['.ipynb_checkpoints', 'App.py', 'app.py.rtf', 'AP_Rainfall.ipynb', 'canals', 'final_risk_map.html', 'rain_model.pkl', 'sample_data.csv', 'Untitled.ipynb']

In [129]:
import geopandas as gpd

canals = gpd.read_file(
    r"C:\Users\shiva reddy\Downloads\Canals-20260403T081042Z-1-001\Canals\Canals.shp"
)

print(canals.head())

                 canal_name    canal_type  length_km  st_length_  \
0               Eluru Canal    Main Canal      94.95    0.882708
1  Western Delta Main Canal    Main Canal      66.19    0.599956
2     Kanigiri Branch Canal  Branch Canal      11.07    0.102272
3           Kommamuru Canal    Main Canal      93.75    0.857060
4             Veligallu LMC    Main Canal       6.82    0.062242

                                            geometry
0  LINESTRING (80.98034 16.61955, 80.98232 16.620...
1  LINESTRING (80.60121 16.49721, 80.60131 16.494...
2  LINESTRING (79.74746 14.58277, 79.74785 14.582...
3  LINESTRING (80.22293 15.64618, 80.22267 15.646...
4  LINESTRING (78.46534 14.03799, 78.46524 14.038...

In [130]:
from shapely.geometry import Point

geometry = [Point(xy) for xy in zip(final_df['centroid_lon'], final_df['centroid_lat'])]

gdf = gpd.GeoDataFrame(final_df, geometry=geometry)

In [131]:
canals = canals.to_crs(epsg=4326)
gdf = gdf.set_crs(epsg=4326)

In [132]:
buffer_zone = canals.buffer(0.01)   # ~1km

In [133]:
risk_area = gdf[gdf.geometry.within(buffer_zone.unary_union)]

print("Nearby villages:", risk_area.shape)

Nearby villages: (126, 15)

In [134]:
features = ['year','month','day','centroid_lat','centroid_lon','rain_lag1','rain_lag2']

risk_area['predicted_rain'] = model.predict(risk_area[features])

In [135]:
def get_risk(rain):
    if rain > 20:
        return "HIGH"
    elif rain > 5:
        return "MEDIUM"
    else:
        return "LOW"

risk_area['risk_level'] = risk_area['predicted_rain'].apply(get_risk)

In [136]:
m.save("final_risk_map.html")

In [137]:
def predict_for_village(village_name, year, month, day):
    
    # get village data
    data = final_df[final_df['village'] == village_name].iloc[-1]
    
    lat = data['centroid_lat']
    lon = data['centroid_lon']
    lag1 = data['rain_lag1']
    lag2 = data['rain_lag2']
    
    # prediction
    rain = model.predict([[year, month, day, lat, lon, lag1, lag2]])[0]
    
    # risk
    if rain > 20:
        risk = "HIGH"
    elif rain > 5:
        risk = "MEDIUM"
    else:
        risk = "LOW"
    
    print("Village:", village_name)
    print("Predicted Rainfall:", rain)
    print("Risk Level:", risk)
    
    return rain, risk, lat, lon

In [139]:
def predict_all(year, month, day):
    
    df_copy = final_df.copy()
    
    # Use same input date for all rows
    df_copy['year'] = year
    df_copy['month'] = month
    df_copy['day'] = day
    
    features = ['year','month','day','centroid_lat','centroid_lon','rain_lag1','rain_lag2']
    
    # Predict
    df_copy['predicted_rain'] = model.predict(df_copy[features])
    
    # Risk logic
    def get_risk(rain):
        if rain > 20:
            return "HIGH"
        elif rain > 5:
            return "MEDIUM"
        else:
            return "LOW"
    
    df_copy['risk_level'] = df_copy['predicted_rain'].apply(get_risk)
    
    # Final table
    result = df_copy[['district','mandal','village','predicted_rain','risk_level']]
    
    return result

In [140]:
result_df = predict_all(2025, 7, 10)

result_df.head()

           district            mandal village  predicted_rain risk_level
63053      Tirupati  Ramachandrapuram  Forest        1.691436        LOW
65392  Y.S.R.Kadapa           Sidhout  Forest        1.679529        LOW
64907  Y.S.R.Kadapa         S.Mydukur  Forest        2.054856        LOW
65168  Y.S.R.Kadapa           Sidhout  Forest        1.691436        LOW
62789      Tirupati            Pakala  Forest        2.042948        LOW

In [141]:
result_df = result_df.sort_values(by='predicted_rain', ascending=False)

In [142]:
high_risk = result_df[result_df['risk_level'] == "LOW"]
high_risk.head()

                     district      mandal village  predicted_rain risk_level
70033              Markapuram     Dornala  Forest        2.418275        LOW
147330  Alluri Sitharama Raju  Dumbriguda  Forest        2.418275        LOW
74042                 Nandyal     Velgode  Forest        2.418275        LOW
149828  Alluri Sitharama Raju      Paderu  Forest        2.418275        LOW
148242  Alluri Sitharama Raju  G Madugula  Forest        2.418275        LOW

In [143]:
mandal_summary = result_df.groupby('mandal')['predicted_rain'].mean().reset_index()
mandal_summary.head()

        mandal  predicted_rain
0  Ananthagiri        1.674388
1      Atmakur        1.734542
2  Chandragiri        1.647648
3      Dornala        1.737419
4   Dumbriguda        1.855362

In [144]:
import pickle
pickle.dump(model, open("rain_model.pkl", "wb"))

final_df.to_csv("sample_data.csv", index=False)

In [145]:
import os
print(os.getcwd())

C:\Users\shiva reddy\AP_Rainfall_Task

In [146]:
gdf[['rain_lag1','rain_lag2']].head(10)

       rain_lag1  rain_lag2
63053   0.800000  14.891676
65392  32.511967   0.800000
64907   1.187019  32.511967
65168   0.105425   1.187019
62789   1.187019   0.105425
62292  16.841194   1.187019
65315  42.776176  16.841194
65548   1.187019  42.776176
63328   1.187019   1.187019
62974   0.800000   1.187019

In [147]:
final_df['village_code'] = final_df['village'].astype('category').cat.codes

In [148]:
features = [
    'year','month','day',
    'centroid_lat','centroid_lon',
    'rain_lag1','rain_lag2',
    'village_code'
]

In [149]:
X = final_df[features]
y = final_df['rainfall_mm']

model.fit(X, y)

RandomForestRegressor(n_estimators=5)

In [155]:
import pickle
pickle.dump(model, open("rain_model.pkl", "wb"))

In [156]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import pickle

# Load data
df = pd.read_csv("sample_data.csv")

# Add date features
df['year'] = 2024
df['month'] = 1
df['day'] = 1

# ❌ REMOVE village_code completely
features = [
    'year','month','day',
    'centroid_lat','centroid_lon',
    'rain_lag1','rain_lag2'
]

target = 'rainfall_mm'

X = df[features]
y = df[target]

# Train model
model = RandomForestRegressor(n_estimators=10)
model.fit(X, y)

# Save new model
pickle.dump(model, open("rain_model.pkl", "wb"))

print("✅ New model saved (without village_code)")

✅ New model saved (without village_code)

In [157]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import pickle

df = pd.read_csv("sample_data.csv")

df['year'] = 2024
df['month'] = 1
df['day'] = 1

features = [
    'year','month','day',
    'centroid_lat','centroid_lon',
    'rain_lag1','rain_lag2'
]

X = df[features]
y = df['rainfall_mm']

model = RandomForestRegressor(n_estimators=10)
model.fit(X, y)

pickle.dump(model, open("rain_model.pkl", "wb"))